---
- hosts: windowspcs

  tasks:
  - name: Create logisim-evolution directory
    win_file:
      path: C:\Programme\logisim-evolution
      state: directory

  - name: grab logisim-evolution jar file
    win_get_url:
      url: http://reds-data.heig-vd.ch/logisim-evolution/logisim-evolution.jar
      dest: C:\Programme\logisim-evolution\logisim-evolution.jar
      
  - name: download logisim icon 
    win_get_url: 
      url: http://a.fsdn.com/allura/p/circuit/icon?1367254782?&w=90
      dest: C:\Programme\logisim-evolution\logisim.png

  - name: install logisim-evolution
    win_lineinfile:
      path: C:\Programme\logisim-evolution\start_logisim.cmd
      line: 'java -jar C:\Programme\logisim-evolution\logisim-evolution.jar'
      create: yes
      regexp: logisim-evolution.jar


  - name: add logisim-evolution to start menu 
    win_shortcut: 
      src:  'C:\Programme\logisim-evolution\start_logisim.cmd'
      dest: 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\logisim-evolution.lnk' 
      directory: 'C:\Programme\logisim-evolution\'
      icon: 'C:\Programme\logisim-evolution\logisim.png'

