---

- name: print username for which config is done 
  debug:
    msg: "{{ localuser }}"
  tags:
  - vlc_mime_test
   
 
- name: ensure config folder 
  file: path="/home2/{{ localuser }}/.config" state=directory owner={{ localuser }} mode=0700
  tags:
  - vlc_mime_test

### configure vlc privacy 

- name: ensure vlc config folder 
  file: path=/home2/{{ localuser }}/.config/vlc state=directory owner={{ localuser }} mode=0700
  tags:
  - vlc_mime_test

- name: copy vlcrc to vlc config folder
  copy: src=vlcrc dest=/home2/{{ localuser }}/.config/vlc/vlcrc
  tags:
  - vlc_mime_test

- name: configure
  lineinfile:
    dest: /home2/{{ localuser }}/.config/vlc/vlcrc
    state: present
    line: "metadata-network-access=0"
    regexp: 'metadata-network-access'
  tags:
  - vlc_mime_test

### mime Associations Video -> VLC

- name: copy mime configuration file to remote machine
  copy: src=mimeapps.list dest=/home2/{{ localuser }}/.config/mimeapps.list owner={{ localuser }} mode=0600
  tags:
  - vlc_mime_test
  
  
    
