---
- hosts: 192.168.200.192
  
## Ubuntu 16.04

  tasks:
  - name: dist upgrade 
    apt:
      upgrade: dist
      update_cache: yes


  - name: install some tools 
    apt:
      name: 
      - rsync
      - sysstat
      - dstat
      - iftop
      - iotop
      - tcpdump
      - tree
      state: present  



