---
- hosts: 172.16.1.37

  tasks:
  - name: Install fail2ban
    apt:
      name: 
      - fail2ban
      state: present

  - name: remove old jail configuration
    file:
      path: "/etc/fail2ban/jail.local"    
      state: absent
      
  - name: enable sshd jail
    blockinfile:
      path: "/etc/fail2ban/jail.local"    
      block: | 
        [sshd]
        enabled = true
      create: yes
      insertafter: BOF
    notify: restart fail2ban

  - name: enable fail2ban
    service:
      name: fail2ban
      enabled: yes
    notify: restart fail2ban
     
      
  handlers:
  - name: restart fail2ban
    service: 
      name:  fail2ban 
      state: restarted 
       
