---

- name: ensure desktop  directory for local user
  file: 
    path: /home2/{{ localuser }}/Schreibtisch
    state: directory 
    mode: 0755
    owner: "{{ localuser }}"

#######################################

- name: copy audioserver.desktop to remote host 1604
  copy:
    src: audioserver.desktop.1604
    dest: /home2/{{ localuser }}/Schreibtisch/audioserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  when: ansible_distribution_version == "16.04"


- name: copy audioserver.desktop to remote host 1804
  copy:
    src: audioserver.desktop.1804
    dest: /home2/{{ localuser }}/Schreibtisch/audioserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  when: ansible_distribution_version == "18.04"


###

- name: copy videoserver.desktop to remote host 1604
  copy:
    src: videoserver.desktop.1604
    dest: /home2/{{ localuser }}/Schreibtisch/videoserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  #when: ansible_distribution_version == "16.04"

- name: copy videoserver.desktop to remote host 1804
  copy:
    src: videoserver.desktop.1804
    dest: /home2/{{ localuser }}/Schreibtisch/videoserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  #when: ansible_distribution_version == "18.04"

###

- name: copy material.desktop to remote host 1604
  copy:
    src: material.desktop.1604
    dest: /home2/{{ localuser }}/Schreibtisch/material.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  #when: ansible_distribution_version == "16.04"

- name: copy material.desktop to remote host 1804
  copy:
    src: material.desktop.1804
    dest: /home2/{{ localuser }}/Schreibtisch/material.desktop
    mode: 0755
    owner: "{{ localuser }}"  
  #when: ansible_distribution_version == "18.04"

### configure icon positioning 16.04 

- name: ensure .config folder
  file: path=/home2/{{ localuser }}/.config state=directory owner={{ localuser }}
  when: ansible_distribution_version == "16.04"

- name: ensure .config/upstart folder
  file: path=/home2/{{ localuser }}/.config/upstart state=directory owner={{ localuser }}
  when: ansible_distribution_version == "16.04"

- name: copy script for icon positioning
  template:
    src: set-icon-positions-serverconnections.conf.j2
    dest: /home2/{{ localuser }}/.config/upstart/set-icon-position_serverconnections.conf
    mode: 0644
    owner: "{{ localuser }}"  
  when: ansible_distribution_version == "16.04"

  
### configure icon positioning 18.04 

- name: ensure .config folder
  file: path=/home2/{{ localuser }}/.config state=directory owner={{ localuser }}
  when: ansible_distribution_version == "18.04"

- name: ensure .config/autostart folder
  file: path=/home2/{{ localuser }}/.config/autostart state=directory owner={{ localuser }}
  when: ansible_distribution_version == "18.04"

- name: copy script for icon positioning
  template:
    src: set-icon-position_serverconnections.sh.j2
    dest: /home2/{{ localuser }}/.config/autostart/set-icon-position_serverconnections.sh
    mode: 0700
    owner: "{{ localuser }}"  
  when: ansible_distribution_version == "18.04"
  
- name: copy desktop file for icon positioning
  copy:
    src: set-icon-position_serverconnections.desktop
    dest: /home2/{{ localuser }}/.config/autostart/set-icon-position_serverconnections.desktop
    mode: 0644
    owner: "{{ localuser }}"  
  when: ansible_distribution_version == "18.04"
  
  
