---
- hosts: inf2pcs
  
 
  roles:
    - ubuntu_clients_20.04/install_software/opt_install_classicmenu-indicator4allusers
    - ubuntu_clients_20.04/configure_domain-logon_autofs-home
    - ubuntu_clients_20.04/configure_domain-logon_autofs-nfsshares
    - ubuntu_clients_20.04/configure_domain-logon_gdm
    - ubuntu_clients_20.04/configure_domain-logon_SSSD-auth
    - ubuntu_clients_20.04/configure_cups-client_and_default-printer
    - ubuntu_clients_20.04/configure_autoshutdown

  tasks:    
  - name: delete password of borgguest
    command: passwd -d borgguest
