---

## copy script to remote

- name: copy connect2home.sh to remote host
  copy:
    src: connect2home.sh
    dest: /usr/local/bin/connect2home.sh
    mode: 0755
    owner: root  

## copy desktop file 

- name: folder Schreibtisch present
  file: path="/home2/{{ localuser }}/Schreibtisch" state=directory mode=0755 owner="{{ localuser }}"


- name: copy connect2home.desktop to remote host
  copy:
    src: connect2home.desktop
    dest: "/home2/{{ localuser }}/Schreibtisch/connect2home.desktop"
    mode: 0755
    owner: "{{ localuser }}"

- name: copy connect2home.desktop to remote host
  copy:
    src: connect2home.desktop
    dest: "/usr/share/applications/connect2home.desktop"
    mode: 0644
    owner: root


- name: ensure .config folder
  file: path="/home2/{{ localuser }}/.config" state=directory owner="{{ localuser }}"  mode=0700


### put script to autostart folder

- name: ensure .config/autostart folder
  file: path="/home2/{{ localuser }}/.config/autostart" state=directory owner="{{ localuser }}"  mode=0700
  when: ansible_distribution_version == "20.04"

- name: copy script for icon positioning
  template:
    src: set-icon-position_connect2home.sh.j2
    dest: "/home2/{{ localuser }}/.config/autostart/set-icon-position_connect2home.sh"
    mode: 0755
    owner: "{{ localuser }}"


- name: copy desktop file for icon positioning to default user
  copy:
    src: set-icon-position_connect2home.desktop
    dest: "/home2/{{ localuser }}/.config/autostart/set-icon-position_connect2home.desktop"
    mode: 0750
    owner: "{{ localuser }}"


    
    
    
    
