---
- hosts: klassenpcs, O2-10-PCV7
  
  vars:
    localuser: admin
    iconposition_x: 1400
    firefox_save_logins: None
    applist_in_launcher_2004: "[ 'ubiquity.desktop', 'webuntis.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop', 'geogebra-classic.desktop', 'vlc.desktop', 'libreoffice-writer.desktop', 'libreoffice-impress.desktop', 'yelp.desktop' ]"

    
  roles:
    - ubuntu_clients_20.04/install_software/opt_install_classicmenu-indicator4allusers
    - ubuntu_clients_20.04/opt__configure-firefox-policies
    - ubuntu_clients_20.04/configure_lehrerkiosk/configure_launcher-webuntis4localuser
    - ubuntu_clients_20.04/configure_defaults4users/set_launcher_in_schemafile
    - ubuntu_clients_20.04/configure_defaults4users/set_unity_defaults
    - ubuntu_clients_20.04/configure_lehrerkiosk/set_appdefaults4localuser-vlc_GDM
    - ubuntu_clients_20.04/configure_lehrerkiosk/configure_desktop-connect2home
    - ubuntu_clients_20.04/configure_lehrerkiosk/configure_desktop-serverconnections-ro
    - ubuntu_clients_20.04/configure_sessionrestart_GDM

    - role: ubuntu_clients_20.04/configure_autoshutdown
      shutdown_time: "10 18"
    
  tasks:
    - name: guest | create user association file for mime type
      lineinfile: 
        dest: /home2/admin/.config/mimeapps.list
        state: present
        create: yes
        line: '[Added Associations]'
        owner: admin 
        mode: 0600  
      
    - name: guest | configure vlc as standard app for iso files
      lineinfile: 
        dest: /home2/admin/.config/mimeapps.list
        state: present
        line: 'application/x-cd-image=vlc.desktop;'
        insertafter: Added.*Associations
        owner: admin 
        mode: 0600


