---

- name: Add partner repo 16.04
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu xenial partner
    state: present
  when: ansible_distribution_version == "16.04"

- name: Add partner repo 18.04
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu bionic partner
    state: present
  when: ansible_distribution_version == "18.04"
  
- name: update apt Cache
  apt: update_cache=yes cache_valid_time=10800
  
- name: update all packages
  apt: upgrade=yes
  
################################
  
### with meta:  Installation des Basissystems mit Desktop 16.04
 
################################

- name: Installation von Grafik-Software 16.04
  apt: name="{{ packages_list_graphics_1604 }}" state=present
  when: ( ansible_distribution_version == "16.04")

- name: Installation von Grafik-Software 18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_graphics_1804 }}"
  when: ( ansible_distribution_version == "18.04") 

################################

- name: Installation von Netzwerk-Software 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_internet_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")

- name: Installation von Netzwerk-Software
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_internet_1804 }}"
  when: ( ansible_distribution_version == "18.04") 

################################

- name: Entfernen von pepperflash 18.04  16.04
  apt: name={{ item }} state=absent purge=yes
  with_items:
    pepperflashplugin-nonfree
    browser-plugin-freshplayer-pepperflash purge=yes
  when: (ansible_distribution_version == "16.04") or  ( ansible_distribution_version == "18.04")

################################

- name: Installation von Adobe Flash 18.04  16.04
  apt: 
    name: adobe-flashplugin
    state: present
  when: (ansible_distribution_version == "16.04") or  ( ansible_distribution_version == "18.04")

################################

- name: Installation von Multimedia-Software 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_multimedia_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")

- name: Installation von Multimedia-Software 18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_multimedia_1804 }}"
  when: ( ansible_distribution_version == "18.04") 
  
################################

- name: Installation von Office-Software 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_office_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")
  
- name: Installation von Office-Software 18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_office_1804 }}"
  when: ( ansible_distribution_version == "18.04") 

################################

- name: Installation von Wissenschaft-Software 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_science_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")
  
  
- name: Installation von Wissenschaft-Software 18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_science_1804 }}"
  when: ansible_distribution_version == "18.04"
  
################################

- name: Installation von Software für Softwareentwicklung 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_softwaredevelopment_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")
  
- name: Installation von Software für Softwareentwicklung 18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_softwaredevelopment_1804 }}"
  when: ansible_distribution_version == "18.04"
  
################################

- name: Installation von weiterer Zubehör Software  16.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_tools_1604 }}"
  when: ( ansible_distribution_version == "14.04") or  ( ansible_distribution_version == "16.04")
    
- name: Installation von weiterer Zubehör Software  18.04
  apt: name={{ item }} state=present
  with_items: "{{ packages_list_tools_1804 }}"
  when: ansible_distribution_version == "18.04"
  
################################  
  
  
  
