---
- hosts: localhost 

  vars:
    ansible_connection: local

  pre_tasks:
  - name: add localhost to hosts list
    add_host: name=localhost groups=linuxpcs

  roles:
  - ubuntu_clients/install_software/install_packages-ubuntu-repo

- import_playbook: management-playbooks/linuxpcs/opt_install_fonts-replacing-cambria-calibri.yml
