---
- hosts: localhost 

  vars:
    ansible_connection: local

  pre_tasks:
  - name: add localhost to hosts list
    add_host: name=localhost groups=linuxpcs

#  - name: include vars from inventory         
#    include_vars: 
#      file: /var/lib/ansible/inventories/borg/group_vars/all.yml

  roles:
  - ubuntu_clients/install_software/install_packages-ubuntu-repo
  
  tasks:
  - name: set distupgrade never
    lineinfile:
      dest: /etc/update-manager/release-upgrades
      state: present
      regexp: "^Prompt="
      line: "Prompt=never"   

  
