---
- hosts: localhost 

  vars:
    ansible_connection: local

  pre_tasks:
  - name: add localhost to hosts list
    add_host: name=localhost groups=linuxpcs


- import_playbook: management-playbooks/linuxpcs/setup_ansible-pull.yml

