---
- hosts: O2-30-PC01 O2-31-PC01 O2-32-PC01

  vars:
    fach: ph
    fach_langbezeichnung: Physik
    localuser: "{{ fach }}-user"

  tasks:
  - name: add repository for picotech
    apt_repository:
      repo: deb http://labs.picotech.com/debian/ picoscope main
      state: present


  - name: copy key for repo
    copy:
      src: Release.gpg.key
      dest: /root/Release.gpg.key

  - name: add key
    apt_key:
      file: /root/Release.gpg.key
      state: present

  - name: install PicoScope Software
    apt:
      name: picoscope
      update_cache: yes


  - name: add application icon to Desktop
    copy:
      remote_src: True
      src: /usr/share/applications/picoscope.desktop
      dest: "/home2/{{ localuser }}/Schreibtisch/picoscope.desktop"
      owner: "{{ localuser }}"
      mode: 0700





