---
- hosts: inf1pcs
  
  roles:
    - ubuntu_clients/install_software/opt_install_classicmenu-indicator4allusers
    - ubuntu_clients/configure_domain-logon_autofs-home
    - ubuntu_clients/configure_domain-logon_autofs-nfsshares
    - ubuntu_clients/configure_domain-logon_lightdm
    - ubuntu_clients/configure_domain-logon_SSSD-auth
    - ubuntu_clients/configure_cups-client_and_default-printer
    - ubuntu_clients/configure_autoshutdown
    
  post_tasks:
  - name: reboot the host
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
      
  - name: wait for host after reboot
    local_action: 
      module: wait_for 
        host="{{inventory_hostname}}" 
        delay=15 
        state=started 
        timeout=60
