---

- name: install flvstreamer
  apt: 
    name: flvstreamer 
    state: present

- name: Installationsscript zum Client kopieren
  copy:
    src: files/install_MediathekView.sh
    dest: /tmp/install_MediathekView.sh

- name: Installation von MediathekView
  command: bash /tmp/install_MediathekView.sh


