---  

### dependency: Installation der radius-Pakete
### dependency:  WLC-1 und WLC2 als Radius-Client konfigurieren (Editieren von /etc/raddb/client.conf )
### dependency: Firewall für Radius Anfragen öffnen

####################################################################################

- name: Konfiguration des LDAP-Moduls (Editieren von /etc/raddb/mods-enabled/ldap )
  copy: 
    src: "{{ ldap_config_file }}"
    dest: /etc/raddb/mods-available/ldap
    backup: yes
    owner: root
    group: radiusd
    mode: 0640 
  
  
- name: LDAP-Modul aktivieren (symbolischen Link setzen)
  file: 
    src: /etc/raddb/mods-available/ldap  
    dest: /etc/raddb/mods-enabled/ldap  
    owner: root 
    group: radiusd 
    state: link


#######################  /etc/raddb/mods-available/eap  ####################################


- name: Konfigurieren von /etc/raddb/mods-available/eap  | gtc im eap-Tunnel
  replace:
    dest: /etc/raddb/mods-available/eap
    regexp: '(eap\s*[^<]*)default_eap_type\s=\s.*([^<]*timer_expire)'
    replace: '\1default_eap_type = gtc\2'
    backup: yes
    
- name:  Konfigurieren von /etc/raddb/mods-available/eap | gtc im ttls-Tunnel   
  replace:
    dest: /etc/raddb/mods-available/eap
    regexp: '(ttls\s*[^<]*)default_eap_type\s=\s.*([^<]*The tunneled authentication)'
    replace: '\1default_eap_type = gtc\2'
    backup: yes  


########################### /etc/raddb/mods-available/eap ###########################
- name: Konfigurieren von /etc/raddb/sites-available/inner-tunnel
  copy:
    src: files/inner-tunnel.v1
    dest: /etc/raddb/sites-available/inner-tunnel
    backup: yes
  



- name: enable and restart service radiusd
  service: name=radiusd enabled=yes state=restarted































