--- 

########################## Benutzer konfigurieren ##################################

- name: install lightdm 
  apt: name=lightdm

- name: preseed display manager | 1
  debconf:
    name: gdm3
    question: shared/default-x-display-manager
    vtype: select
    value: "lightdm"
  notify: restart lightdm
  when: ansible_distribution_version == "18.04"


- name: preseed display manager | 2
  debconf:
    name: lightdm
    question: shared/default-x-display-manager
    vtype: select
    value: "lightdm"
  notify: restart lightdm

- name: configure lightdm as default display manager
  lineinfile: line="/usr/sbin/lightdm" dest="/etc/X11/default-display-manager" state=present insertafter=BOF regexp='/usr/sbin'
  notify: restart lightdm

- name: reconfigure lightdm package
  shell: dpkg-reconfigure -f noninteractive lightdm

- name: reconfigure gdm package
  shell: dpkg-reconfigure -f noninteractive gdm3
  when: ansible_distribution_version == "18.04"

- name: enable guest session in lightdm
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
    line: "allow-guest=true" 
    state: present 
    regexp: '\w*allow-guest\w*=' 
  when: ansible_distribution_version == "18.04"

  
### create directory for local accounts

- name: create home2  
  file: path=/home2 state=directory mode=0755 owner=root


### Benutzer konfigurieren -> lokales Administratorkonto einrichten
- name: Benutzerkonto admin einrichten
  user: 
    name: admin
    comment: admin 
    groups: sudo 
    home: /home2/admin
    shell: /bin/bash
    password: $6$xOeCh1dvtS4Q$zlzsTRMsBUBB93TUWY91ESbMZWHxoltKya9HRKjpn0gLhwFvOyMFvdUSkcB01DXjntXuVP7VsyNAy6wuqtUuC.


### Benutzer konfigurieren -> Konto für Gastkonfiguration einrichten
- name: Benutzerkonto guest-prefs einrichten
  user: 
    name: guest-prefs
    uid: 1011
    comment: Gastkonfiguration 
    home: /home2/guest-prefs
    shell: /bin/bash
    password: $6$xOeCh1dvtS4Q$zlzsTRMsBUBB93TUWY91ESbMZWHxoltKya9HRKjpn0gLhwFvOyMFvdUSkcB01DXjntXuVP7VsyNAy6wuqtUuC.
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")


### Benutzer konfigurieren -> guest-session und guest-prefs verlinken

- name: create directory guest-session
  file: path=/etc/guest-session state=directory mode=0755 owner=root


- name: create link from /home2/guest-prefs to guest-session  
  file: src=/home2/guest-prefs dest=/etc/guest-session/skel state=link


### copy small scripts for changing autologin/noautologin

- name: copy lightdmconfiguration files to remote host
  copy: src=lightdm.conf.autologin dest=/etc/lightdm/lightdm.conf.autologin owner=root mode=0644
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")

- name: copy lightdmconfiguration files to remote host
  copy: src=lightdm.conf.noautologin dest=/etc/lightdm/lightdm.conf.noautologin owner=root mode=0644
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")

- name: copy lightdmconfiguration files to remote host
  copy: src=change-to-autologin.sh dest=/root/change-to-autologin.sh owner=root mode=0700
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")

- name: copy lightdmconfiguration files to remote host
  copy: src=change-to-noautologin.sh dest=/root/change-to-noautologin.sh owner=root mode=0700
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")

### copy script to copy monitors.xml

- name: copy script for copying monitors.xml
  copy: src=copy_monitor.xml_to_guest-prefs.sh dest=/root/copy_monitor.xml_to_guest-prefs.sh owner=root mode=0755
  when: (ansible_distribution_version == "16.04") or (ansible_distribution_version == "18.04")






  
