---

- name: ensure desktop  directory for local user
  file: 
    path: /home2/{{ localuser }}/Schreibtisch
    state: directory 
    mode: 0755
    owner: "{{ localuser }}"

#######################################

- name: copy audioserver.desktop to remote host
  copy:
    src: audioserver.desktop
    dest: /home2/{{ localuser }}/Schreibtisch/audioserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  

- name: copy audioserver.desktop to remote host
  copy:
    src: audioserver.desktop
    dest: /usr/share/applications/audioserver.desktop
    mode: 0644
    owner: root 

###

- name: copy videoserver.desktop to remote host
  copy:
    src: videoserver.desktop
    dest: /home2/{{ localuser }}/Schreibtisch/videoserver.desktop
    mode: 0755
    owner: "{{ localuser }}"  

- name: copy videoserver.desktop to remote host
  copy:
    src: videoserver.desktop
    dest: /usr/share/applications/videoserver.desktop
    mode: 0644
    owner: root  

###

- name: copy material.desktop to remote host
  copy:
    src: material.desktop
    dest: /home2/{{ localuser }}/Schreibtisch/material.desktop
    mode: 0755
    owner: "{{ localuser }}" 

- name: copy material.desktop to remote host
  copy:
    src: material.desktop
    dest: /usr/share/applications/material.desktop
    mode: 0644
    owner: root  
  
### configure icon positioning 

- name: ensure .config folder
  file: path=/home2/{{ localuser }}/.config state=directory owner={{ localuser }}


- name: ensure .config/autostart folder
  file: path=/home2/{{ localuser }}/.config/autostart state=directory owner={{ localuser }}


- name: copy script for icon positioning
  template:
    src: set-icon-position_serverconnections.sh.j2
    dest: /home2/{{ localuser }}/.config/autostart/set-icon-position_serverconnections.sh
    mode: 0700
    owner: "{{ localuser }}"  

  
- name: copy desktop file for icon positioning
  copy:
    src: set-icon-position_serverconnections.desktop
    dest: /home2/{{ localuser }}/.config/autostart/set-icon-position_serverconnections.desktop
    mode: 0644
    owner: "{{ localuser }}"  

  
  
