---
- hosts: maturapcs

  vars: 
    filename: KL21_PT1_ALL_ENG_HO_B2_SF.mp3
#    filename: test.txt

  tasks:
  - name: copy mp3 to desktop
    copy:
      src: "{{filename}}"
      dest: "/home2/admin/Schreibtisch/"

#- hosts: O2-07-PC01
#  vars: 
#    filename: KL19_PT1_ALL_FRA_HO_B1_SF.mp3#
#
#  tasks:
#  - name: copy mp3 to windows desktop
#    win_copy:
#      src: "{{filename}}"
#      dest: 'C:\ProgramData\Desktop\'

