---
- hosts: lehrerpcs-ph O2-10-PCT2

  vars:
    localuser: "{{ fach }}-user"

  roles:
  - ubuntu_clients/configure_lehrerkiosk/configure_create_localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_autologin4localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_gsettings4localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_desktop-connect2home
  - ubuntu_clients/configure_lehrerkiosk/configure_desktop-serverconnections-fach_autofs
  - ubuntu_clients/configure_lehrerkiosk/configure_launcher-webuntis4localuser
  - ubuntu_clients/configure_lehrerkiosk/set_appdefaults4localuser-vlc
  
  
  post_tasks:
  - name: restart lightdm
    service:
      name: lightdm
      state: restarted
