---
- hosts: lehrerpcs_konf
  
  vars:
    localuser: "{{ fach }}-user"
    
  roles:
  - ubuntu_clients/configure_lehrerkiosk/configure_create_localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_autologin4localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_gsettings4localuser
  - ubuntu_clients/configure_lehrerkiosk/configure_desktop-connect2home
  - ubuntu_clients/configure_lehrerkiosk/configure_launcher-webuntis4localuser
  - ubuntu_clients/configure_lehrerkiosk/set_appdefaults4localuser-vlc
  #- ubuntu_clients/configure_lehrerkiosk/configure_desktop-serverconnections-rw_in_userspace   ## problem
  - ubuntu_clients/configure_lehrerkiosk/configure_desktop-serverconnections-ro
  - ubuntu_clients/install_software/opt_install_mediathekview   ## problem
  
  tasks:
  - name: Mediathek-Icon auf den Desktop kopieren   
    copy:
      remote_src: true 
      src: /usr/share/applications/mediathekview.desktop 
      dest: "/home2/{{ localuser }}/Schreibtisch"
      owner: "{{ localuser }}"
      mode: 0700
       
  post_tasks:
  - name: restart lightdm
    service:
      name: lightdm
      state: restarted
