---
- hosts: boss

  vars:
    use_message: use    ap -e 'host_to_provision=O2-10-PCV7' 11_create_VM-Ubuntu-pve.yml
    host_to_provision: "{{ use_message }}"
    hostname_client: "{{ host_to_provision }}"
    release: "20.04"
    architecture: "x86_64"
    pve_server: pve2
    pve_storage: NFS-Storage
    
    
  pre_tasks:
  - name: these hosts will be created
    debug: var=host_to_provision
    tags: create_vms

  - meta: end_play
    when: host_to_provision==use_message

  - name:
    set_fact:
      macaddresses_of_hostnames: {}
  
  
  - name: create VM in pve
    proxmox_kvm:
      api_host: "{{ pve_server }}"
      api_user: root@pam
      api_password: "{{ hostvars['pve2']['server_password'] }}"
      name        : "{{ hostname_client }}"
      # vmid: 
      node        : "{{ pve_server }}"
      cores       : 4 
      memory      : 4096
      # ostype:   #for some guests only
      # update      : yes
      #sata: 	'{"sata0":"local-lvm:20,format=raw"}'
      sata: 	'{"sata0":"{{ pve_storage }}:40,format=qcow2"}'
      #scsihw	  : virtio-scsi-pci | lsi
      #virtio      : '{"virtio0":"pve-storage:30"}'
      #
      net         : '{"net0":"virtio,bridge=vmbr0,tag=140"}'
    delegate_to: "{{ pve_server }}"
    register: vm_return


  - name: MAC get
    set_fact:
      macaddress: "{{ vm_return.mac.net0 }}"
      cacheable: yes
      
  - name: build dict
    set_fact:
      macaddresses_of_hostnames: "{{ macaddresses_of_hostnames | combine({ hostname_client :macaddress }) }}"

  - name: print hostname mac dictionary
    debug: var=macaddresses_of_hostnames
     
   
  - name: wait 10s until VM has been created
    wait_for:
      timeout: 10
    delegate_to: localhost
    
  - name: first boot of new VM
    proxmox_kvm:
      api_host: "{{ pve_server }}"
      api_user: root@pam
      api_password: "{{ hostvars['pve2']['server_password'] }}"
      name        : "{{ hostname_client }}"
      node        : "{{ pve_server }}"
      state: started
    delegate_to: "{{ pve_server }}"
 

  tasks:
  - name: create entry in dhcpd.conf   
    include_role:
      name: do_minimal_networkinstallations_unattended
    vars:
      create_entry_for_host: True     
    
  - name: wait 60s until VM has booted
    wait_for:
      timeout: 60

    
  - name: remove entry from dhcpd.conf   
    include_role:
      name: do_minimal_networkinstallations_unattended
    vars:
      create_entry_for_host: False     
      


