---
- hosts: boss

  vars:
    hostname_client: "O2-10-PCV9"
    release: "20.04"
    architecture: "x86_64"
    
    
  pre_tasks:
  - name:
    set_fact:
      macaddresses_of_hostnames: {}
  
  
  - name: create VM in pve01
    proxmox_kvm:
      api_host: pve01
      api_user: root@pam
      api_password: "{{ hostvars['pve01']['server_password'] }}"
      name        : "{{ hostname_client }}"
      # vmid: 
      node        : pve01
      cores       : 2 
      memory      : 4096
      # ostype:   #for some guests only
      # update      : yes
      sata		   : '{"sata0":"pve-storage:30,format=raw"}'
      #scsihw	  : virtio-scsi-pci | lsi
      #virtio      : '{"virtio0":"pve-storage:30"}'
      #
      net         : '{"net0":"virtio,bridge=vmbr1,tag=140"}'
    delegate_to: pve01
    register: vm_return


  - name: MAC get
    set_fact:
      macaddress: "{{ vm_return.mac.net0 }}"
      cacheable: yes
      
  - name: build dict
    set_fact:
      macaddresses_of_hostnames: "{{ macaddresses_of_hostnames | combine({ hostname_client :macaddress }) }}"

  - name: print hostname mac dictionary
    debug: var=macaddresses_of_hostnames
     
   
  - name: wait 10s until VM has been created
    wait_for:
      timeout: 10
    delegate_to: localhost
    
  - name: first boot of new VM
    proxmox_kvm:
      api_host: pve01
      api_user: root@pam
      api_password: "{{ hostvars['pve01']['server_password'] }}"
      name        : "{{ hostname_client }}"
      node        : pve01
      state: started
    delegate_to: pve01
 
 
#  roles:
 # - role: do_minimal_networkinstallations_unattended
  #  create_entry_for_host: True
    

  tasks:
  - name: create entry in dhcpd.conf   
    include_role:
      name: do_minimal_networkinstallations_unattended
    vars:
      create_entry_for_host: True     
    
  - name: wait 60s until VM has booted
    wait_for:
      timeout: 60

    
  - name: remove entry from dhcpd.conf   
    include_role:
      name: do_minimal_networkinstallations_unattended
    vars:
      create_entry_for_host: False     
      


