---

- name: copy zoom client deb to host
  copy: 
    src: "zoom_amd64.deb"
    dest: /tmp/zoom_amd64.deb
    owner: root 
    group: root 
    mode: 0644
 

- name: install vncviewer
  apt: 
    deb: /tmp/zoom_amd64.deb
    state: present
    
    
    
