--- 
  
### remove some packages

- name: remove some packages
  apt: 
    name:
    - bluez-alsa 
    - bluez-utils 		#
    - network-manager-pptp 		#
    - network-manager-pptp-gnome		#
    state: absent 

- name: autoremove packages
  apt: update_cache=yes autoremove=yes

