---
- hosts: boss   ## DHCP-Server
                ## wird so konfiguriert, dass der Client eine Netzwerk-Installation durchführt

  vars:
    hostname_client: "basicserver"   			## 
    macaddress_client: "DA:AE:BE:78:87:E1" 


  roles:
  - server/install-unattended-CentOS8

