---

- hosts: localhost
  gather_facts: False

  vars: 
    group: "{{ groups['bibliothekpcs'] }}"
  
  tasks:
  - name: Alle Linux-PCs in der Bibliothek aufwecken
    local_action: command /usr/local/bin/wake_with_foginfo.sh "{{ item }}"
    with_items: "{{ group }}"

