---
- hosts: boss   ## DHCP-Server
                ## wird so konfiguriert, dass der Client eine Netzwerk-Installation durchführt

  vars:
    macaddresses_of_hostnames: { "O2-10-PCV6": "1A:E0:CA:CC:AC:A1", "O2-10-PCV7": "86:80:3B:15:CF:56" }
    create_entry_for_host: True


###### defaults
#   release: "16.04"
#   architecture: "x86_64"
#
####### examples  


  roles:
  - do_minimal_networkinstallations_unattended


