---

- hosts: localhost
  gather_facts: False

  vars: 
    group: "{{ groups['lehrerpcs-konf'] }}"
  
  tasks:
  - name: Alle Linux-PCs aufwecken
    local_action: command /usr/local/bin/wake_with_foginfo.sh "{{ item }}"
    with_items: "{{ group }}"

