---
- hosts: klassenpcs
  
  vars:
    localuser: guest-prefs
    iconposition_x: 1100
    firefox_save_logins: None
    applist_in_launcher_1804: "[ 'ubiquity.desktop', 'webuntis.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop', 'geogebra-classic.desktop', 'vlc.desktop', 'libreoffice-writer.desktop', 'libreoffice-impress.desktop', 'yelp.desktop' ]"

    
  roles:
    - ubuntu_clients/install_software/opt_install_classicmenu-indicator4allusers
    - ubuntu_clients/opt__configure-firefox-policies
    - ubuntu_clients/configure_lehrerkiosk/configure_autologin4guest
    - ubuntu_clients/configure_lehrerkiosk/configure_launcher-webuntis4localuser
    - ubuntu_clients/configure_defaults4users/set_launcher_in_schemafile
    - ubuntu_clients/configure_lehrerkiosk/set_appdefaults4localuser-vlc
    - ubuntu_clients/configure_lehrerkiosk/configure_desktop-connect2home
    - ubuntu_clients/configure_lehrerkiosk/configure_desktop-serverconnections-ro
    - ubuntu_clients/configure_sessionrestart

    - role: ubuntu_clients/configure_autoshutdown
      shutdown_time: "10 18"
    
  tasks:
    - name: guest | create user association file for mime type
      lineinfile: 
        dest: /home2/guest-prefs/.config/mimeapps.list
        state: present
        create: yes
        line: '[Added Associations]'
        owner: guest-prefs 
        mode: 0600  
      
    - name: guest | configure vlc as standard app for iso files
      lineinfile: 
        dest: /home2/guest-prefs/.config/mimeapps.list
        state: present
        line: 'application/x-cd-image=vlc.desktop;'
        insertafter: Added.*Associations
        owner: guest-prefs 
        mode: 0600
        
  
  
  post_tasks:
    - name:  restart lightdm 
      shell: /bin/systemctl restart lightdm
      when:  ansible_distribution_version == "16.04" 

    - name:  restart lightdm 
      shell: /usr/sbin/service lightdm restart
      when:  ansible_distribution_version == "18.04" 


