---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"


- name: Install the required  packages in Redhat derivatives
  yum: name='{{ item }}' state=installed
  with_items: "{{ network_pkgs }}"
  when: ansible_os_family == 'RedHat'


- name: Create the network configuration file for ethernet devices
  template: 
    src: ethernet_RedHat.j2 
    dest: "{{ net_path + '/ifcfg-' + ansible_interfaces[1] }}"
    backup: yes
    force: yes 

## hostname wird mit kickstart konfiguriert; set domain for FQDN
#
 
- name: reset hostname
  command: hostnamectl set-hostname ""

- name: set hostname
  command: hostnamectl set-hostname "{{ host_name + '.' + domain_name }}"


#- name: restart network
#  command: nmcli connection reload



