---

### classicmenu


- name: install classicmenu-indicator
  apt: name=classicmenu-indicator state=installed
  when: ( ansible_distribution_version == "16.04" )


- name: ensure classicmenu-indicator in /opt
  file: path=/opt/classicmenu-indicator state=directory owner=root group=root mode=0755
  when: ( ansible_distribution_version == "16.04" )

- name: copy icon to remote host
  copy: src=classicmenu-indicator.png dest=/opt/classicmenu-indicator/classicmenu-indicator.png owner=root group=root mode=0644
  when: ( ansible_distribution_version == "16.04" )

- name: ensure config folder 
  file: path=/home2/{{ localuser }}/.config state=directory owner={{ localuser }} group={{ localuser }} mode=0700
  when: ( ansible_distribution_version == "16.04" )

- name: ensure classicmenu-indicator folder in config 
  file: path=/home2/{{ localuser }}/.config/classicmenu-indicator state=directory owner={{ localuser }} group={{ localuser }} mode=0700
  when: ( ansible_distribution_version == "16.04" )

- name: copy classicmenu-indicator config-file to .config/classicmenu-indicator/
  copy: src=config.json dest=/home2/{{ localuser }}/.config/classicmenu-indicator/config.json owner={{ localuser }} group={{ localuser }} mode=0700
  when: ( ansible_distribution_version == "16.04" )

