---
- hosts: linuxpcs

         
  tasks:   
  - name: add ppa repository for ansible
    apt_repository:
      repo: ppa:ansible/ansible
      state: present

  - name: update apt cache
    apt: update_cache=yes

  - name: update ansible to latest version
    apt: name=ansible state=latest
    notify:
    - reboot_machine  

  - name: add cronjob for ansible update and setup ansible-pull
    lineinfile:
      path: /etc/cron.d/ansible-pull
      create: yes
      regexp: "@reboot"
      line: '@reboot root bash -c "sleep 20 && /usr/bin/ansible-pull -U https://github.com/edvborg/ansible_manage_schools.git -d /var/lib/ansible/ update_ansible-pull.yml >> /var/log/ansible.log 2>&1 ;  /usr/bin/ansible-pull -U https://github.com/edvborg/ansible_manage_schools.git -d /var/lib/ansible/ setup_ansible-pull.yml >> /var/log/ansible.log 2>&1"    '   
    notify: reboot_machine

        
  handlers:
  - name: reboot_machine
    reboot: 
 

