---
- hosts: linuxpcs

  pre_tasks:
  - name: ensure apt-transport-https
    apt: name=apt-transport-https state=latest
   
  - name: remove old opera version
    apt:
      name: opera
      state: absent
      
  - name: remove old opera repos 1
    file: path=/etc/apt/sources.list.d/deb_opera_com_opera.list state=absent
    
  - name: remove old opera repos 2
    file: path=/etc/apt/sources.list.d/opera.list state=absent


  roles:
  - ubuntu_clients/install_software/install_update_opera


  tasks:
  - name: show version 
    command: opera --help
    register: result

  - name: print output from Opera 
    debug: var=result.stdout_lines[0]




