---
- hosts: linuxpcs

  tasks:
  - name: ensure apt-transport-https
    apt: name=apt-transport-https state=latest
   
  - name: remove old opera version
    apt:
      name: opera
      state: absent
      
  - name: remove old opera repos 1
    file: path=/etc/apt/sources.list.d/deb_opera_com_opera.list state=absent
    
  - name: remove old opera repos 2
    file: path=/etc/apt/sources.list.d/opera.list state=absent

  - name: add key  for repo
    apt_key:  
      url: http://deb.opera.com/archive.key
      state: present

  - name: add repository for opera
    apt_repository:
      repo: deb https://deb.opera.com/opera-stable stable non-free 
      filename: deb_opera_com_opera
      state: present

  - name: install opera
    apt: name=opera-stable update_cache=yes

  - name: show version 
    command: opera --help
    register: result

  - name: print output from Opera 
    debug: var=result.stdout_lines[0]




