---

- name: copy vncviewer deb to host
  copy: 
    src: "VNC-Viewer-6.20.113-Linux-x64.deb"
    dest: /root/vncviewerx64.deb
    owner: root 
    group: root 
    mode: 0644
 

- name: install vncviewer
  apt: 
    deb: /root/vncviewerx64.deb
    state: present
    
    
    
