---

### configure webuntis desktop file 

- name: ensure webuntis directory
  file: path=/opt/webuntis state=directory 


- name: copy Webuntis Icon to remote machine
  copy: src=webuntis.png dest=/opt/webuntis/webuntis.png


- name: ensure desktop folder 
  file: path=/home2/guest-prefs/Schreibtisch state=directory owner=guest-prefs mode=0700


- name: copy desktopfile to remote machine
  copy: src=webuntis.desktop dest=/usr/share/applications/webuntis.desktop owner=root mode=0644


- name: remove old desktop file
  file: path=/home2/guest-prefs/Schreibtisch/untis.desktop state=absent

- name: copy desktopfile to Guest User
  copy: src=webuntis.desktop dest=/home2/guest-prefs/Schreibtisch/webuntis.desktop owner=guest-prefs mode=0700


### configure autostart for webuntis

- name: ensure config folder 
  file: path=/home2/guest-prefs/.config state=directory owner=guest-prefs mode=0700


- name: ensure autostart folder 
  file: path=/home2/guest-prefs/.config/autostart state=directory owner=guest-prefs mode=0700

- name: remove old desktop file
  file: path=/home2/guest-prefs/.config/autostart/untis.desktop state=absent

- name: copy desktopfile to Guest User/autostart
  copy: src=webuntis.desktop dest=/home2/guest-prefs/.config/autostart/webuntis.desktop owner=guest-prefs mode=0700




