---
- hosts: boss   ## DHCP-Server
                ## wird so konfiguriert, dass der Client eine Netzwerk-Installation durchführt

  vars:
    hostname_client: "testmaschine-2020"   			## 
    macaddress_client: "00:0c:29:62:2E:DF" 


  roles:
  - server/install-unattended-CentOS7

