--- 

## install virtualbox extension pack
- name: install virtualbox-ext-pack
  apt: name=virtualbox-ext-pack state=latest


## winontop

- name: create dir for winontop
  file: path={{ virtualmachines_path }}/winontop/ state=directory mode=0775 group=sudo

- name: create tmp dir in virtualmachines path
  file: path="{{ virtualmachines_path }}/winontop/tmp" state=directory mode=1777   

- name: copy script to client | 1
  copy: 
    src: startVM.sh
    dest: "{{ virtualmachines_path }}/winontop/startVM.sh"
    mode: 0755
    owner: root
    group: root
     
- name: copy script to client | 2
  copy: 
    src: start-and-configureVM.sh
    dest: "{{ virtualmachines_path }}/winontop/start-and-configureVM.sh"
    mode: 0750
    owner: root
    group: sudo
    
- name: copy Icon to client
  copy: 
    src: win10.png
    dest: "{{ virtualmachines_path }}/winontop/win10.png"
    mode: 0644
    owner: root
    group: root

- name: copy desktopfile to client
  template: 
    src: win10.desktop.j2
    dest: "{{ virtualmachines_path }}/winontop/win10.desktop"
    mode: 0755
    owner: root
    group: root

- name: copy desktopfile to applications dir
  template: 
    src: win10.desktop.j2
    dest: /usr/share/applications/win10.desktop
    mode: 0644
    owner: root
    group: root
  
    
#- name: rsync VDI file
#   synchronize:  src="/netzordner/{{ virtualbox_machines_dir }}/win10.vdi" dest="{{ virtualmachines_path }}/winontop/win10.vdi" partial=yes archive=yes
#  delegate_to: "{{ inventory_hostname }}"
#  become: yes
#  become_user: admin

- name: rsync VDI file
  shell: 'rsync -au /netzordner/{{ virtualbox_machines_dir }}/win10.vdi {{ virtualmachines_path }}/winontop/win10.vdi'
  become: yes
  become_user: admin


