---

- name: ensure opera-stable installed
  apt: name=opera-stable state=present 

- name: opera | copy modified desktop file to remote
  copy: 
    src: opera.desktop
    dest: /usr/share/applications/opera.desktop
    backup: yes
    
    

