---
- hosts: inf2pcs inf1pcs inf3pcs

  vars: 
    url_shortname: "Sportpsychologische Testung"

  tasks:
  - name: remove desktop file with link from guest account
    file: 
      path: /etc/guest-session/skel/Schreibtisch/chromium-browser_{{ url_shortname }}.desktop
      state: absent

      
      
