---
- hosts: linuxpcs
  
  roles:
##
  - ubuntu_clients/configure_auto_hostname
##
## 
  - ubuntu_clients/configure_defaults4machine/configure_default-user_and_guest-user
  - ubuntu_clients/configure_defaults4machine/configure_network_and_dns
  - ubuntu_clients/configure_defaults4machine/configure_ntp-client
  - ubuntu_clients/configure_defaults4machine/configure_smb-client
  - ubuntu_clients/configure_defaults4machine/disable_some_services
  - ubuntu_clients/configure_defaults4machine/remove_amazon_from_menu
  - ubuntu_clients/configure_defaults4machine/remove_packages_and_autoclean

## defaults for all users

  - ubuntu_clients/configure_defaults4users/set_unity_defaults
  - ubuntu_clients/configure_defaults4users/disable_user_services
  - ubuntu_clients/configure_defaults4users/set_opera_cachedir-in-tmp
  - ubuntu_clients/configure_defaults4users/set_firefox_startup-homepage
  - ubuntu_clients/configure_defaults4users/set_firefox_cachedir-in-tmp

##
## configure desktop env for default user (for klassenpcs, lehrerkiosk) 

  - ubuntu_clients/configure_session_for_defaultuser/set_appdefaults4localuser-vlc
  
  tasks:
  - name: set distupgrade never
    lineinfile:
      dest: /etc/update-manager/release-upgrades
      state: present
      regexp: "^Prompt="
      line: "Prompt=never"   

  
  post_tasks:
  - name: restart networking
    shell: sleep 2 && systemctl restart networking
    async: 1
    poll: 0
    ignore_errors: true

  - name: restart network manager
    shell: sleep 2 && systemctl restart NetworkManager
    async: 1
    poll: 0
    ignore_errors: true    

      
  - name: wait for host after network restart
    local_action: 
      module: wait_for 
        host="{{inventory_hostname}}" 
        delay=1 
        state=started 
        timeout=2
  
  - name: restart lightdm
    service: name=lightdm state=restarted
