---

- name: install mysql client
  apt:
    name: mysql-client
    state: present
    
       
- name: Installationsscript zum Client kopieren 16.04
  copy:
    src: set_hostname_with_fog-16.04-fog1.4.4.sh
    dest: /usr/local/sbin/set_hostname_with_fog.sh
    mode: 0700
  when: (ansible_distribution_version == "16.04") or  ( ansible_distribution_version == "18.04")

      
- name: remove old cronjob
  file: path=/etc/cron.d/configure-hostname state=absent
  

- name: configure cron for starting hostname script at reboot
  lineinfile:
    dest: /etc/cron.d/set_hostname_with_fog
    create: yes
    regexp: "@reboot"
    line: "@reboot root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games; sleep 40 && /usr/local/sbin/set_hostname_with_fog.sh >> /var/log/hostnamechange.log 2>&1" 
    
