---
- name: redhat | Installing Pre-Reqs
  yum:
    name: "lldpd"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

  
- name: redhat | Configuring Interfaces
  template:
    src: "etc/sysconfig/network-scripts/ifcfg.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ network_interface }}"
  notify: 
  - restart machine
  - wait for host after network restart

- name: deactivate network manager
  service: name=NetworkManager enabled=no

- name: enable network service
  service: name=network enabled=yes
   


