--- 

### Installation von ntp sicherstellen

- name: Installation von ntp
  apt: name=ntp state=present update_cache=yes
  when: ansible_distribution_version == "16.04"


### Sicherstellen, dass ntpdate nicht installiert ist; Konflikt mit ntp

- name: Entfernen von ntpdate
  apt: name=ntpdate state=absent 
  when: ansible_distribution_version == "16.04"
     
 
### configure ntp 

- name: configure ntp 
  lineinfile:
    dest: /etc/ntp.conf
    state: present
    backup: yes
    regexp: '^\s*server.*'
    line: "server 192.168.200.254" 
    insertbefore: '^#server\s*127.*'
  notify: reload ntp
  when: ansible_distribution_version == "16.04"

### enable ntp service
- name: enable ntp service
  service: name=ntp enabled=yes 
  notify: reload ntp

