---

### configure webuntis desktop file 

- name: ensure webuntis directory
  file: path=/opt/webuntis state=directory 

- name: copy Webuntis Icon to remote machine
  copy: src=webuntis.png dest=/opt/webuntis/webuntis.png

- name: ensure desktop folder 
  file: path=/home2/{{ localuser }}/Schreibtisch state=directory owner={{ localuser }} group={{ localuser }}  mode=0755

- name: copy desktopfile to remote machine
  copy: src=webuntis.desktop dest=/usr/share/applications/webuntis.desktop owner=root mode=0644

- name: copy desktopfile to Local User
  copy: src=webuntis.desktop dest=/home2/{{ localuser }}/Schreibtisch/webuntis.desktop owner={{ localuser }} mode=0700
  when: ansible_distribution_version == "14.04"
 

### configure autostart for webuntis

- name: ensure config folder 
  file: path=/home2/{{ localuser }}/.config state=directory owner={{ localuser }} group={{ localuser }} mode=0700


- name: ensure autostart folder 
  file: path=/home2/{{ localuser }}/.config/autostart state=directory owner={{ localuser }} group={{ localuser }} mode=0700


- name: copy desktopfile to local user/autostart
  copy: src=webuntis.desktop dest=/home2/{{ localuser }}/.config/autostart/webuntis.desktop owner={{ localuser }} group={{ localuser }} mode=0700


### configure upstart for user

- name: ensure .config folder
  file: path=/home2/{{ localuser }}/.config state=directory mode=0700 owner={{ localuser }} group={{ localuser }}

- name: ensure .config/upstart folder
  file: path=/home2/{{ localuser }}/.config/upstart state=directory  mode=0700 owner={{ localuser }} group={{ localuser }}
  when: ansible_distribution_version == "16.04"
  
- name: copy script for setting apps in launcher
  template:
    src: set-apps-in-launcher.conf.j2
    dest: /home2/{{ localuser }}/.config/upstart/set-apps-in-launcher.conf
    mode: 0644
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
  when: ansible_distribution_version == "16.04"
