---
# file: group_vars/all
ansible_connection: ssh 
ansible_user: root 


###############################################################################################################
##########################   SERVER  ##########################################################################
###############################################################################################################

##########################################################
### Domain 
#   domain_name: "borg-ibk.local"
#
tld: "local"
sld: "borg-ibk"
domain_name: "{{ sld + '.' + tld }}"

dns_nameservers:
  - 192.168.200.200

dns_search: "{{ domain_name }}"
domain_sid: "S-1-5-21-2336030208-1547323707-3435355501"  

##########################################################
### LDAP-Server
ldapserver_address: 192.168.200.200
ldapserver_netmask: 255.255.255.0
ldapserver_gateway: 192.168.200.254
ldapserver2_address: 192.168.200.201
ldapserver2_netmask: 255.255.255.0
ldapserver2_gateway: 192.168.200.254


ldap_base_dn: "{{ 'dc=' +  sld +',dc=' + tld }}" 
ldap_users_base_dn: "ou=people,{{ ldap_base_dn }}"
ldap_schueler_base_dn: "ou=schueler,{{ ldap_users_base_dn }}"
ldap_lehrer_base_dn: "ou=lehrer,{{ ldap_users_base_dn }}"
ldap_groups_base_dn: "ou=groups,{{ ldap_base_dn }}"
ldap_uri: "ldap://{{ ldapserver_address }}"


##########################################################
### Samba-Server
samba_address: 192.168.200.205
samba_netmask: 255.255.255.0
samba_gateway: 192.168.200.254
samba4_address: 192.168.200.206
samba4_netmask: 255.255.255.0
samba4_gateway: 192.168.200.254

##########################################################
### nextcloud-Server
cloud_address: 192.168.200.207
cloud_netmask: 255.255.255.0
cloud_gateway: 192.168.200.254
cloud_address_dmz: 172.16.1.38
cloud_netmask_dmz: 255.255.255.0
cloud_gateway_dmz: 172.16.1.254

##########################################################
### CUPS-Server
cups_address: 192.168.200.220
cups_netmask: 255.255.255.0
cups_gateway: 192.168.200.254
cups2_address: 192.168.200.223
cups2_netmask: 255.255.255.0
cups2_gateway: 192.168.200.254

##########################################################
### TFTP-Server == FOG

tftpserver_address: 192.168.200.231
tftpserver_netmask: 255.255.255.0
tftpserver_gateway: 192.168.200.254


##########################################################
### Backups-Server

backupserver_address: 192.168.200.225
backupserver_netmask: 255.255.255.0
backupserver_gateway: 192.168.200.254




##########################################################
### Radius-Server

radiusserver_address: 192.168.200.203
radiusserver_netmask: 255.255.255.0
radiusserver_gateway: 192.168.200.254

radiusserver2_address: 192.168.200.204
radiusserver2_netmask: 255.255.255.0
radiusserver2_gateway: 192.168.200.254

###############################################################################################################
########################## FOR CLIENTS ####################################################################
###############################################################################################################


# http_filerepo_url: http://www.borg-ibk.tsn.at/Downloads
http_filerepo_url: http://wiki.borg-ibk.local/files
switch_ssh_username: rudi

