--- 

########################## GDM konfigurieren ##################################

- name: enable automatic login
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "AutomaticLoginEnable = true" 
    state: present
    regexp: '^#  AutomaticLoginEnable'
    insertafter: '[daemon]'


- name: set user for automatic login
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "AutomaticLogin = borgguest" 
    state: present
    regexp: 'AutomaticLogin'
    insertafter: '[daemon]' 


- name: enable timed login
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "TimedLoginEnable = true" 
    state: present
    regexp: 'TimedLoginEnable'
    insertafter: '[daemon]' 


- name: set user for timed login
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "TimedLogin = borgguest" 
    state: present
    regexp: 'TimedLogin'
    insertafter: '[daemon]' 


- name: set timed login delay
  lineinfile:
    dest: /etc/gdm3/custom.conf
    line: "TimedLoginDelay = 0" 
    state: present
    regexp: 'TimedLoginDelay'
    insertafter: '[daemon]'
  notify: restart gdm3


  
### create directory for local accounts

- name: create home2  
  file: path=/home2 state=directory mode=0755 owner=root


### Benutzer konfigurieren -> lokales Administratorkonto einrichten
- name: Benutzerkonto admin einrichten
  user: 
    name: admin
    comment: admin 
    groups: sudo 
    home: /home2/admin
    shell: /bin/bash
    password: $6$xOeCh1dvtS4Q$zlzsTRMsBUBB93TUWY91ESbMZWHxoltKya9HRKjpn0gLhwFvOyMFvdUSkcB01DXjntXuVP7VsyNAy6wuqtUuC.


### Benutzer konfigurieren -> Konto für Gastkonfiguration einrichten
- name: Benutzerkonto borgguest einrichten
  user: 
    name: borgguest
#    uid: 1011
    comment: Gastkonfiguration 
    home: /tmp/borgguest
    shell: /bin/bash
    password: $6$xOeCh1dvtS4Q$zlzsTRMsBUBB93TUWY91ESbMZWHxoltKya9HRKjpn0gLhwFvOyMFvdUSkcB01DXjntXuVP7VsyNAy6wuqtUuC.


### copy script for home dir of guestuser
- name: copy Default script to /etc/gdm3/PostLogin/
  copy: src=Default_PostLogin dest=/etc/gdm3/PostLogin/Default owner=root mode=0755


### copy script to restart gdm3 after session
- name: copy Default script to /etc/gdm3/PostSession/
  copy: src=Default_PostSession dest=/etc/gdm3/PostSession/Default owner=root mode=0755





