--- 

- name: install autofs package
  apt: name={{item}} state=present
  with_items:
    - nfs-common 
    - autofs5

- name: create entry for auto.home
  lineinfile:
    dest: /etc/auto.master
    state: present
    backup: yes
    regexp: "/home"
    line: "/home	/etc/auto.home    --ghost"


- name: copy auto.home.fs1 to remote host
  copy:
    src: auto.home.fs1
    dest: /etc/auto.home
    mode: 0644
    owner: root  

- name: reload autofs
  service: name=autofs enabled=yes state=restarted


