---


###########################################################################

- name: create kickstartfile on tftp server
  template:
    src: 'basic-centos7-ks.cfg.j2'
    dest: '/opt/autoinstall/redhat-serverconfiguration/kickstart.files/basic-centos7-ks.cfg'
  delegate_to: laus   


- name: configure DHCP-Server for unattended client installation
  template:
    src: 'dhcpd.declare-host.j2'
    dest: '/etc/dhcp/dhcpd.{{ hostname_client }}.conf'

- name: include host_declaration_file in dhcpd.conf
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
    mode: 0640
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK <DHCP>"
    block: |

       include "/etc/dhcp/dhcpd.{{ hostname_client }}.conf";  
      
    insertafter: ".*Deklarationen mit Ansible.*"	

- name: check dhcpd.conf
  command: dhcpd -t 
  register: dhcpdstatus
  ignore_errors: true


- name: restart dhcpd service
  command: service dhcpd restart 
  when: dhcpdstatus.rc == 0


- name: Client mit WOL starten   ### not working (router configuration )
  command: /usr/bin/wol -i {{ item}} {{ macaddress_client }}
  with_items:
   - "192.168.100.0"
   - "192.168.110.0"
   - "192.168.120.0"
   - "192.168.130.0"
   - "192.168.140.0"
  delegate_to: laus

- name: abwarten bis Installation gestartet ist
  pause:
    minutes: 1


- name: remove host_declaration_file in dhcpd.conf
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
    mode: 0640
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK <DHCP>"
    block: |

       include "/etc/dhcp/dhcpd.{{ hostname_client }}.conf";  
      
    insertafter: ".*Deklarationen mit Ansible.*"


- name: check dhcpd.conf
  command: dhcpd -t 
  register: dhcpdstatus
  ignore_errors: true


- name: restart dhcpd service
  command: service dhcpd restart 
  when: dhcpdstatus.rc == 0	



