---
- hosts: O2-02-PC01,O2-03-PC01

  tasks:
  - name: ensure config dir for default user
    file:
      path: "/home2/{{ fach }}-user/.config/"
      mode: 0700
      state: directory
      owner: "{{ fach }}-user"
    
  - name: copy monitors.xml from ansible to guest account 
    copy:
      src: monitorfiles/{{ inventory_hostname }}/monitors.xml
      dest: "/home2/{{ fach }}-user/.config/monitors.xml"
      owner: "{{ fach }}-user"
      mode: 0664

