---
- hosts: switches
  connection: local

  vars:
    cli:
      host: UG-04-SW02
      username: rudi
      password: borgibk
  
  
  tasks:
  - name: run show version
    ios_command:
      provider: "{{ cli }}"
      commands: 'show version'
    register: result

      
  - name: print output
    debug: 
      var: result.stdout_lines  

