--- 

- name: copy certificate to client
  copy: 
    src: boss.borg-ibk.local.pem
    dest: /etc/ssl/certs/boss.borg-ibk.local.pem
    mode: 644
    owner: root
    group: root
  notify: reload services sssd and lightdm
     
- name: configure openldap client
  copy: 
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
    mode: 644
    owner: root
    group: root
  notify: reload services sssd and lightdm
     
- name: install packages for LDAP Authentication
  apt: 
    name:
    - sssd
    - sssd-tools
    - libsasl2-modules-ldap  
    state: present
  notify: reload services sssd and lightdm
    
- name: create sssd.conf
  template: 
    src:  sssd.conf.j2  
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: reload services sssd and lightdm
  
  
