---

- name: ensure apt-transport-https
  apt: name=apt-transport-https state=latest



##################################### Opera ########################################

   
- name: add key  for repo
  apt_key:  
    url: "http://deb.opera.com/archive.key"
    id: "68E9B2B03661EE3C44F707504B8EC3BAABDC4346"
    state: present


- name: add repository for opera
  apt_repository:
    repo: deb https://deb.opera.com/opera-stable/ stable non-free # Opera Browser (final releases) 
    filename: opera-stable
    state: present

- name: install opera
  apt: name=opera-stable update_cache=yes state=latest

