---
- hosts: linuxpcs
  
  tasks:  
  - name: add ppa repository for musescore3
    apt_repository:
      repo: ppa:mscore-ubuntu/mscore3-stable
      state: present


  - name: install musescore 3 latest
    apt: 
      name:
      - musescore3
      state: latest 
#      only_upgrade: yes
      update_cache: yes 
#      cache_valid_time: 3600

# uncomment for only update #
