---
- hosts: linuxpcs

  tasks:
  - name: reboot the host
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
      
  - name: wait for host after reboot
    local_action: 
      module: wait_for 
        host="{{inventory_hostname}}" 
        delay=15 
        state=started 
        timeout=60  


